### ISSUE TITLE
个别页面下可以打开，但控制台会提示如下错误

### ISSUE THREAD

**Issue by armink** [iPeng6/docsify-sidebar-collapse#14]
感谢大神提供的非常棒的插件，就是最近用的时候发现，在有些页面下，会控制台提示如下错误，该如何定位呢

![image](https://user-images.githubusercontent.com/1734686/98247103-29251a00-1fae-11eb-909f-ee2ff2f15e69.png)

**Comment by iPeng6** [comment]
有发布出来的页面吗，或者哪个仓库我本地起来看看

**Comment by armink** [comment]
打包好了，你可以试试，多谢啦

[docsify-sidebar-collapse-test2.zip](https://github.com/iPeng6/docsify-sidebar-collapse/files/5501511/docsify-sidebar-collapse-test2.zip)

**Comment by iPeng6** [comment]
已修复

**Comment by armink** [comment]
太棒了，大神这效率真高 👍

**Comment by armink** [comment]
如何能够拿到发布后代码呢？ CDN 上好像还是旧版本的 //cdn.jsdelivr.net/npm/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js

**Comment by iPeng6** [comment]
浏览器强制刷新
mac cmd+shift+r
win ctrl+F5

**Comment by armink** [comment]
> 浏览器强制刷新
> mac cmd+shift+r
> win ctrl+F5

搞定啦，多谢了哈
