### ISSUE TITLE
Feature request: add configuration of sidebar display level

### ISSUE THREAD

**Issue by nash900** [iPeng6/docsify-sidebar-collapse#19]
Current the sidebar will collapse by default to display only level 1 title (level a1, level b1).
Does it possible to add a level configuration (1~N) to display level N title? 
For example if N is two, then sidebar display like this:
- Level a1
  - Level a21
  - Level a22
- Level b1
  - Level b21
  - Level b22

Example _sidebar.md:
```
- Level a1
  - Level a21
  - Level a22
    - Level a31
    - Level a32
- Level b1
  - Level b21
  - Level b22
    - Level b31
    - Level b32
```

Thanks.

**Comment by ivandov** [comment]
Came here to request exactly this. Please consider this request.

**Comment by iPeng6** [comment]
ok I will think about it asap

**Comment by iPeng6** [comment]
```html
<script>
  window.$docsify = {
    ...
    sidebarDisplayLevel: 1, // set sidebar display level
  }
</script>
```
we can config it like above now，then just refresh your web,  use `cmd+shift+r / ctrl + f5` to make sure reload without cache

**Comment by ivandov** [comment]
Works perfectly! Thank you!

**Comment by nash900** [comment]
It's so good! Thank you very much!
