### ISSUE TITLE
导航栏会消失

### ISSUE THREAD

**Issue by HZ-GeLiang** [iPeng6/docsify-sidebar-collapse#20]
inex.html 有如下片段, 

    <nav>
        <a href="#/">首页</a>
        <a href="#/docs/zh-cn/">中文</a>
        <a href="#/docs/en/">EN</a>
    </nav>
添加js后 
<script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js"></script>
导航会消失

**Comment by iPeng6** [comment]
放在`<div id="app"></div>`这个里面的内容会被docsify替换掉，不知道你的nav是放哪里的

**Comment by HZ-GeLiang** [comment]
> 放在`<div id="app"></div>`这个里面的内容会被docsify替换掉，不知道你的nav是放哪里的

复现步骤
1.创建项目 docsify init
![image](https://user-images.githubusercontent.com/16562680/105509717-c3bd0b80-5d08-11eb-93fe-48b8f1916d81.png)
2.修改html,在body下方, 代码 ` <div id="app"></div>` 之前,加入代码片段
```

<nav>
    <a href="#/">首页</a>
    <a href="#/docs/zh-cn/">中文</a>
    <a href="#/docs/en/">EN</a>
</nav>

```
![image](https://user-images.githubusercontent.com/16562680/105509927-04b52000-5d09-11eb-8a0c-1484d8c8ec27.png)

3.启动服务  docsify serve  在页面在右上角会出现导航
![image](https://user-images.githubusercontent.com/16562680/105510099-35955500-5d09-11eb-9e75-de525d50e4bb.png)

4.再次修改html, 在底部添加script
```
<script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
 <script src="//cdn.jsdelivr.net/npm/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js"></script>
```
![image](https://user-images.githubusercontent.com/16562680/105510187-51006000-5d09-11eb-8be2-ff1cd53fe283.png)
此时右上角导航消失
![image](https://user-images.githubusercontent.com/16562680/105510308-73927900-5d09-11eb-878f-60a6d5cdc4c5.png)

**Comment by HZ-GeLiang** [comment]
还发现一个bug, 
1.创建项目 docsify init
2.直接添加script
3.启动项目
4.缩小浏览器尺寸,此时左下角的 三 这个图标, 点击后无法实现左侧导航条隐藏的效果,

**Comment by iPeng6** [comment]
![image](https://user-images.githubusercontent.com/15159415/105859923-06902380-6028-11eb-8cf2-8be9f2c6eed2.png)
这个docsify的主库不要重复引用
