### ISSUE TITLE
每篇文章的第一个标题有时会不显示

### ISSUE THREAD

**Issue by ShXDler** [iPeng6/docsify-sidebar-collapse#23]
![图片](https://user-images.githubusercontent.com/50830775/114863870-e4d25b80-9e22-11eb-956d-1a8785e4687a.png)

如图所示，侧边栏的目录有时候会不显示第一个标题，同时还会显示出它所有的子标题，请问这是为什么啊

**Comment by iPeng6** [comment]
有可以访问的demo吗？

**Comment by ShXDler** [comment]
您看这个网站 https://shxdler.com/#/README

**Comment by iPeng6** [comment]
可能一个文章只能有一个大标题 `#` ,剩下都得从二级标题开始 `##`

**Comment by ShXDler** [comment]
奥奥 调整了以后好像就没问题了 感谢~
