### ISSUE TITLE
dist import

### ISSUE THREAD

**Issue by albesdev** [iPeng6/docsify-sidebar-collapse#7]
Why are you importing   <script src="//unpkg.com/docsify-sidebar-collapse/dist/docsify-sidebar-collapse.min.js">
and not the dist/docsify-sidebar-collapse.min.js file installed on dist directory?

**Comment by iPeng6** [comment]
[unpkg ](https://unpkg.com/)is a fast, global content delivery network for everything on npm. Use it to quickly and easily load any file from any package. I have released the file to unpkg so that everyone can easily reference it.
